### ISSUE TITLE
Cannot read property 'profile' of undefined

### ISSUE THREAD

**Issue by matthew-walter-works** [paypal/rallyslack#6]
Hi RallySlack,

Just trying out your framework today but getting errors. I think it is either a bug or a miss understanding on my part. I am getting a 'Cannot read property 'profile' of undefined'. I have included my config (Figure 1) and the error (Figure 2). 

I could not figure out what the slackWebKey was for simply creating a Bot. Even with the following issue that was closed: https://github.com/paypal/rallyslack/issues/1. So i created a new Slack App via (https://*.slack.com/apps/new/RANDOMNUMBER) and was supplied with 
1) Bot Oauth Access Token (slackBotKey?)
2) But User OAuth Access Token (slackWebKey?)

When typing in Slack it would trigger the error in Figure 2. However was not able to enable information coming from Rally.

Please correct the error of my ways.

Thanks!
-matt

# Figure 1) Config
`"slackbot": {
      "bot": "./bot/bot",
      "slackBotKey": "xoxb-**", 
      "slackWebKey": "xoxp-**"
    },

  "config": {

    "modules": {

      "capture": {
          "path": "./bot/capture/capture",
          "loadIgnore": true
      },

      "rally": {
          "path": "./lib/rally/rally",
          "options": {
            "aliasPath": "./lib/rally/lib/alias.json",
            "configPath": "./lib/rally/config.json",
            "rallyKey": "_***"
          }
      },
*** omitted for brevity ***
`

# Figure 2) Error:
error:  TypeError: Cannot read property 'profile' of undefined
    at Request.slackWeb.userInfo.err [as _callback] (C:\CE\rallyslack\bot\logger.js:25:38)
    at Request.self.callback (C:\CE\rallyslack\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\CE\rallyslack\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\CE\rallyslack\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)

**Comment by dhruvmishra** [comment]
@Xerxous and @rootid23, do you have some idea why user would come undefined.
https://github.com/paypal/rallyslack/blob/master/bot/logger.js#L25

Can you help Matt here?

**Comment by Xerxous** [comment]
Just created an issue for a refactor on the code so that the missing `slackWebKey` won't cause the bot the crash. For further clarification on the slackWebKey, it was necessary to retrieve the detailed information of the user such as first/last as registered in Slack. Without it, the bot is only able to show the username.

This fix will make the slackWebKey optional for those who don't wish to use it.

**Comment by LewisYatesRTH** [comment]
Hi, 

I am also getting the same issue!

I have taken out the slackWebKey, but still the same issue persists.

Cheers!
